# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Encription.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(340, 530)
        Form.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(50, 60, 51, 20))
        self.label.setStyleSheet("color: rgb(0, 85, 0);")
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(120, 60, 171, 22))
        self.comboBox.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color:rgb(255, 255, 255)")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(Form)
        self.comboBox_2.setGeometry(QtCore.QRect(120, 100, 171, 22))
        self.comboBox_2.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color:rgb(255, 255, 255)")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(120, 140, 171, 20))
        self.lineEdit.setStyleSheet("color: rgb(0, 85, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(120, 180, 171, 20))
        self.lineEdit_2.setStyleSheet("color: rgb(0, 85, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(40, 100, 71, 20))
        self.label_2.setStyleSheet("color: rgb(0, 85, 0);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(40, 140, 61, 20))
        self.label_3.setStyleSheet("color: rgb(0, 85, 0);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(30, 180, 71, 20))
        self.label_4.setStyleSheet("color: rgb(0, 85, 0);")
        self.label_4.setObjectName("label_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(Form)
        self.lineEdit_3.setGeometry(QtCore.QRect(120, 220, 171, 20))
        self.lineEdit_3.setStyleSheet("color: rgb(0, 85, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(70, 220, 31, 20))
        self.label_5.setStyleSheet("color: rgb(0, 85, 0);")
        self.label_5.setObjectName("label_5")
        self.lineEdit_4 = QtWidgets.QLineEdit(Form)
        self.lineEdit_4.setGeometry(QtCore.QRect(120, 260, 171, 20))
        self.lineEdit_4.setStyleSheet("color: rgb(0, 85, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(30, 260, 71, 20))
        self.label_6.setStyleSheet("color: rgb(0, 85, 0);")
        self.label_6.setObjectName("label_6")
        self.lineEdit_5 = QtWidgets.QLineEdit(Form)
        self.lineEdit_5.setGeometry(QtCore.QRect(120, 300, 171, 20))
        self.lineEdit_5.setStyleSheet("color: rgb(0, 85, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(10, 300, 91, 20))
        self.label_7.setStyleSheet("color: rgb(0, 85, 0);")
        self.label_7.setObjectName("label_7")
        self.comboBox_3 = QtWidgets.QComboBox(Form)
        self.comboBox_3.setGeometry(QtCore.QRect(120, 20, 171, 22))
        self.comboBox_3.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color:rgb(255, 255, 255)")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(20, 20, 81, 20))
        self.label_8.setStyleSheet("color: rgb(0, 85, 0);")
        self.label_8.setObjectName("label_8")
        self.lineEdit_6 = QtWidgets.QLineEdit(Form)
        self.lineEdit_6.setGeometry(QtCore.QRect(120, 350, 171, 20))
        self.lineEdit_6.setStyleSheet("color: rgb(0, 85, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(60, 350, 41, 20))
        self.label_9.setStyleSheet("color: rgb(0, 85, 0);")
        self.label_9.setObjectName("label_9")
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(40, 440, 75, 23))
        self.pushButton_8.setStyleSheet("QPushButton\n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"background-color : rgb(0, 0, 127);\n"
"}\n"
"QPushButton::hover\n"
"{\n"
"background-color : rgb(0, 0, 255);\n"
"color:white;\n"
"}\n"
"QPushButton::pressed\n"
"{\n"
"background-color :rgb(0, 0, 127)  ;\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setGeometry(QtCore.QRect(220, 440, 75, 23))
        self.pushButton_9.setStyleSheet("QPushButton\n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"background-color : rgb(0, 0, 127);\n"
"}\n"
"QPushButton::hover\n"
"{\n"
"background-color : rgb(0, 0, 255);\n"
"color:white;\n"
"}\n"
"QPushButton::pressed\n"
"{\n"
"background-color :rgb(0, 0, 127)  ;\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "NETWORK"))
        self.comboBox.setItemText(0, _translate("Form", "Local"))
        self.comboBox.setItemText(1, _translate("Form", "Global"))
        self.comboBox_2.setItemText(0, _translate("Form", "AES"))
        self.comboBox_2.setItemText(1, _translate("Form", "RSA"))
        self.comboBox_2.setItemText(2, _translate("Form", "MDB5"))
        self.comboBox_2.setItemText(3, _translate("Form", "FPE"))
        self.comboBox_2.setItemText(4, _translate("Form", "3DES"))
        self.comboBox_2.setItemText(5, _translate("Form", "PGP"))
        self.comboBox_2.setItemText(6, _translate("Form", "BLOW FISH"))
        self.comboBox_2.setItemText(7, _translate("Form", "TWO FISH"))
        self.comboBox_2.setItemText(8, _translate("Form", "CEASER"))
        self.label_2.setText(_translate("Form", "ENCRYPTION"))
        self.label_3.setText(_translate("Form", "PUBLIC KEY"))
        self.label_4.setText(_translate("Form", " PRIVATE KEY"))
        self.label_5.setText(_translate("Form", "NAME"))
        self.label_6.setText(_translate("Form", "SERVER_PORT"))
        self.label_7.setText(_translate("Form", "SERVER_ADDRESS"))
        self.comboBox_3.setItemText(0, _translate("Form", "DATASAVING"))
        self.comboBox_3.setItemText(1, _translate("Form", "CLEARDATAINTIME"))
        self.comboBox_3.setItemText(2, _translate("Form", "NODATA"))
        self.label_8.setText(_translate("Form", " OPERATE DATA"))
        self.label_9.setText(_translate("Form", "Channel"))
        self.pushButton_8.setText(_translate("Form", "Create"))
        self.pushButton_9.setText(_translate("Form", "Save"))
