# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ServerUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1049, 576)
        Form.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(180, 50, 171, 20))
        self.lineEdit.setStyleSheet("color: rgb(0, 85, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lineEdit.setObjectName("lineEdit")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(70, 100, 91, 20))
        self.label_7.setStyleSheet("color: rgb(0, 85, 0);")
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(90, 50, 71, 20))
        self.label_6.setStyleSheet("color: rgb(0, 85, 0);")
        self.label_6.setObjectName("label_6")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(180, 100, 171, 20))
        self.lineEdit_2.setStyleSheet("color: rgb(0, 85, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(460, 50, 75, 23))
        self.pushButton_8.setStyleSheet("QPushButton\n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"background-color : rgb(0, 0, 127);\n"
"}\n"
"QPushButton::hover\n"
"{\n"
"background-color : rgb(0, 0, 255);\n"
"color:white;\n"
"}\n"
"QPushButton::pressed\n"
"{\n"
"background-color :rgb(0, 0, 127)  ;\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setGeometry(QtCore.QRect(460, 100, 75, 23))
        self.pushButton_9.setStyleSheet("QPushButton\n"
"{\n"
"    color: rgb(255, 255, 255);\n"
"background-color : rgb(0, 0, 127);\n"
"}\n"
"QPushButton::hover\n"
"{\n"
"background-color : rgb(0, 0, 255);\n"
"color:white;\n"
"}\n"
"QPushButton::pressed\n"
"{\n"
"background-color :rgb(0, 0, 127)  ;\n"
"color: rgb(255, 255, 255);\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.textEdit_2 = QtWidgets.QTextEdit(Form)
        self.textEdit_2.setGeometry(QtCore.QRect(580, 20, 441, 521))
        self.textEdit_2.setStyleSheet("color: rgb(0, 255, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(Form)
        self.textEdit_3.setGeometry(QtCore.QRect(20, 200, 441, 351))
        self.textEdit_3.setStyleSheet("color: rgb(0, 255, 0);\n"
"background-color: rgb(0, 0, 0);")
        self.textEdit_3.setObjectName("textEdit_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_7.setText(_translate("Form", "SERVER_ADDRESS"))
        self.label_6.setText(_translate("Form", "SERVER_PORT"))
        self.pushButton_8.setText(_translate("Form", "Start"))
        self.pushButton_9.setText(_translate("Form", "Stop"))
